# Generated by Django 4.1.6 on 2023-02-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('review', models.TextField(verbose_name='Review')),
                ('emotion_predict', models.CharField(max_length=10, verbose_name='Predict target')),
                ('rating_predict', models.IntegerField(verbose_name='Predict rating')),
                ('date', models.DateTimeField(verbose_name='Date')),
            ],
        ),
    ]
