# Generated by Django 4.1.6 on 2023-02-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='emotion_predict',
            field=models.CharField(max_length=10, null=True, verbose_name='Predict target'),
        ),
        migrations.AlterField(
            model_name='article',
            name='rating_predict',
            field=models.IntegerField(null=True, verbose_name='Predict rating'),
        ),
    ]
