# Generated by Django 4.1.6 on 2023-02-13 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_article_date_alter_article_emotion_predict_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date',
        ),
    ]
